spring:
  application:
    name: planet-manager
  data:
      elasticsearch:
          cluster-name: evoluting-universe
          cluster-nodes: apeldoorn.gerardverbeek.nl:9201

server:
  port: 9100


application:
  task:
    updateKnownPlanets:
      interval: 5000
    exportStats:
      interval: 2000

elasticsearch:
  stats:
    indexName: stats

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    ROOT: INFO
    eu.luminis: DEBUG

